### PR TITLE
Fixed #19: Removed unnecessary underscores added by sed

### LINKED ISSUE #19: Continent field empty
I tried my own ip adress and the ip adresses in the readme gif but the continent field is always empty.

### PR DESCRIPTION
**Pull request by Costinteo**
Late to solve it, but here it is.

### CODE REVIEW

**Comment by trakBan** [comment]
It worked for me before and it showed flags for countries with spaces in them. When i went to test this pr the output was all messed up.

```
[tb@tra  -------------------- ebja		
cat: /u  Latitude: {removed for privacy}Is a directory
         Longitude: {removed for privacy}	
	 ASN: {removed for privacy}	

[tb@trak ~]$
```

**Comment by Costinteo** [comment]
Ah, I know what the problem is. I messed up the sed by suppressing output. I'll push a commit in a few seconds.

**Comment by trakBan** [comment]
The problem is still present, using [Papua New Guinea or any other 3 name country](https://www.nirsoft.net/countryip/pg.html), ip address results in the same output as i have pasted above.

**Comment by Costinteo** [comment]
Yep. Sorry for the hasty fix. I also forgot to use global flag for sed, to replace all spaces with underscores. Should work now.

Thanks a lot for the good testing!

**Comment by trakBan** [comment]
Thanks for being so quick on making fixes, i have tested your pr and its working.

**Pull request merged**
