### PR TITLE
Replaced sed with jq

### LINKED ISSUE #19: Continent field empty
I tried my own ip adress and the ip adresses in the readme gif but the continent field is always empty.

### PR DESCRIPTION
**Pull request by ghost**
Using sed to parse json files is not a good option, so i replaced it with jq.

The only bad thing about that is jq has to be installed by the user. However I have added some installation instructions for the readme.

It also somehow fixes #19.

### CODE REVIEW

**Comment by Costinteo** [comment]
This is a lot cleaner, but it indeed adds a dependency to the script. Personally I'd rather not have another dependency, especially that's not installed by default, but I agree that it looks a lot better.

That's just my opinion, it's up to @trakBan to decide. :)

**Comment by trakBan** [comment]
When i was initially writing this i really wanted to avoid using jq or any other third party dependencies so users can run this without bloating their systems. I belive i can fix this pretty easily by chaning the regex. Still thanks for spending time to improve this code but i cannot add any third party dependencies.

**Comment by insanolanbiri** [comment]
@trakBan what about using the built in json module in python?

**Comment by trakBan** [comment]
@insanolanbiri thats how i did it before but that was really inefficient and error handling was almost impossible.
https://github.com/trakBan/ipfetch/commit/9f706411f646fcacfd319005f966a198f7bd6a3d

**Pull request closed without merging**
