### PR TITLE
Revamped argument parsing, added usage and refactored code in functions

### PR DESCRIPTION
**Pull request by Costinteo**
Hi, I'm back with some minor improvements.

There's also some issues I've left open for others to contribute. For example, a for loop and dictionary / associative array could fix the repetitive sed calls, if done correctly. I'll open up an issue regarding the suggestions that you could leave open for others to contribute, if they wish. :)

### CODE REVIEW

**Comment by trakBan** [comment]
I probably messed up -h output when trying to fix merge conflicts. Thanks for making this PR, i will probably add some more cursor positions to make letters closer to the flag.

**Comment by Costinteo** [comment]
> I probably messed up -h output when trying to fix merge conflicts. Thanks for making this PR, i will probably add some more cursor positions to make letters closer to the flag.

I only now noticed I messed up the echo due to my tabs. I'll make a PR to fix those and also fix the merge, if that's okay. No need to add cursor positions.

**Comment by trakBan** [comment]
i already did, its only one cursor position, not a big deal.

**Comment by Costinteo** [comment]
@trakBan related to this PR:
You merged your argument parsing and help print as well. You might want to get rid of those? Or get rid of mine if you don't like them. :D
Those are now redundant:
https://github.com/trakBan/ipfetch/blob/294db1d2a0dc5d290beabb88cf5ce3962782679f/ipfetch#L5-L15

Also remove empty line 18, after cat (because it prints an empty line in the help text):
https://github.com/trakBan/ipfetch/blob/294db1d2a0dc5d290beabb88cf5ce3962782679f/ipfetch#L16-L24

**Comment by trakBan** [comment]
I kinda overlooked that when i was solving merge conflicts, i will fix it now.

**Comment by Costinteo** [comment]
@trakBan This is still left in:
https://github.com/trakBan/ipfetch/blob/ee2d986e96bbdd1ff822465eeca8d8d843cfef15/ipfetch#L5-L9

The argument parsing will take care of the IP, no need for extra branches. :) You can remove it.

**Pull request merged**
